### ISSUE TITLE
Peer Review - Linux

### ISSUE THREAD

**Issue by k-rtik** [OpenLiberty/draft-guide-intellij#7]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instructions and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
  - [x] Define test coverage and review with team (including guide contributor, if available)
  - [x] Define detail test cases 
  - [x] Consider corner cases targeting the specific guide
  - [x] Consider different platform tests, ie, Mac, Windows, Linux
  - [x] Consider corner cases UI tests
  - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
  - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
  - [x] Table of contents 
  - [x] Headings
  - [x] Paragraphs
  - [x] code snippets
  - [x] outputs
  - [x] links
  - [x] hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by TrevCraw** [comment]
The test section for this guide does not look complete

**Comment by jj-zhang** [comment]
@TrevCraw Would you mind providing more details about this?

**Comment by TrevCraw** [comment]
@jj-zhang The "Running the tests" section is not in the main flow. _pom.xml_ shows up at the end with the "Running the tests" section inside of it. So that looks like a formatting issue. 

![image](https://user-images.githubusercontent.com/5885743/71990681-d221ad80-3201-11ea-991a-955026c33b75.png)

Content looks to also be lacking as there is no mention of the _EndpointIT.java_ in the instructions. Are we supposed to create that file? Modify it in any way? In the other guides, if a file shows up on the right, the user is supposed to do something with it.

Done

**Comment by TrevCraw** [comment]
Title should be "Using IntelliJ to develop **a** microservice"

Done

**Comment by TrevCraw** [comment]
Received this error when trying to use "Run finish" the first time:
![image](https://user-images.githubusercontent.com/5885743/72023359-880bec80-3240-11ea-82af-2b7aaf73f9e1.png)
I needed to specify the project JDK. This should be added as a step earlier or there should be a note along the lines of "if you see this error, do this"

Done

**Comment by TrevCraw** [comment]
I don't really understand the point of these 3 sections: "Creating the application", "Configuring the server", and "Running the microservice".

It seems like the intention is to start up the service, make an update, and then see that update automatically applied with dev mode. I see no difference in the service after _server.xml_ is updated.

"Creating the application" doesn't make sense to me as the user is not creating anything here, just running it. In the "Configuring the server" section, it states... "To get the service running, the Open Liberty server needs to be correctly configured." ... but the service was already running.

**Comment by TrevCraw** [comment]
This line: "From the menu bar, select Debug and click Check in the pop-up window to start the debugger.", found in the "Debugging the microservice" section should be updated to say something like "select Run in the menu bar and click Run... Then select Check in the pop-up window to start the debugger." This keeps things consistent with all the steps that came before. "Debug" is not an option from the menu bar.

Done

**Comment by TrevCraw** [comment]
In the final paragraph of the "Running the tests" section, it mentions the user can use the "Stop finish" command to exit development mode and stop the server, but this is incorrect. The user is not running the server from the "finish" directory anymore. If there needs to be an option like that, the user will need to create a configuration that will stop the server running in the "start" directory.

Done

**Comment by TrevCraw** [comment]
Is there any way to provide a "copy to clipboard" option for any of the text that the guide is asking users to copy and paste into IntelliJ menus?

Done

**Comment by jj-zhang** [comment]
@TrevCraw 
> I don't really understand the point of these 3 sections: "Creating the application", "Configuring the server", and "Running the microservice".

The intention of creating those three titles are that it should be consistent with another guide RESTful web service https://openliberty.io/guides/rest-intro.html#creating-a-jax-rs-application

**Comment by TrevCraw** [comment]
@jj-zhang I don't really see the parallels between what this guide is doing versus what the JAX-RS guide is doing. The JAX-RS guide actually has the user create a file under the "Create application" section. The IntelliJ guide does not do that. The JAX-RS guide does not have the user run the application and see it working before asking them to "correctly configure" the server in the "Configuring the server" section as the IntelliJ guide does. And in the "Building and running the application" section for the JAX-RS guide, there is something new that the user has done that they can now see. There is nothing new to see in that section for the IntelliJ guide.

**Comment by TrevCraw** [comment]
- [x] The link under `Creating a RESTful web service` points to https://openliberty.io/guides/rest-intro.html#creating-the-jax-rs-resource. It should probably not contain the subsection in the link; just point to the main page.

**Comment by TrevCraw** [comment]
In the "Getting started section":

- [x] `Select View in the menu bar and navigate to Tool Windows and click Project to show up the Project Tool Window...` should say `display` instead of `show up`.

- [x] `At the lower right of the IDE, click Terminal to open the console if needed.`
The Terminal window button is located in the lower left for me on both Linux and Windows.

**Comment by TrevCraw** [comment]
- [x] For the `Configure the build project` section, I would recommend changing the instructions for placing text in the fields to go in order from top down. It's not very user friendly to jump around to different fields in a random order. Should be `Name` field, then `Working_directory` field, then `Command line` field.

**Comment by TrevCraw** [comment]
- [x] `select the path or navigate to the finish directory`
Are these not the same thing? Not sure what else `select the path` could mean

**Comment by TrevCraw** [comment]
- [x] The `Configure the build project` section could be condensed. All four paragraphs have the exact same instructions, the only difference is the values to put in the fields. The first paragraph should be fully written out, but the next three should be simplified.

Something along the lines of....
```
Repeat the above steps using the following values in the corresponding fields:
`Name` field: `Stop finish`
`Working_directory` field: navigate to the finish directory
`Command line` field: `liberty:stop`

Run through the steps again using the following values in the corresponding fields:
....

One last time, using the following values in the corresponding fields:
....
```

**Comment by TrevCraw** [comment]
- [ ] `You can also use the icons on the toolbar to toggle quickly between the different configurations that were set up previously.`

Does this mean the drop down menu in the toolbar?
![image](https://user-images.githubusercontent.com/5885743/72652063-5804cd80-3953-11ea-88b9-745ee506b21b.png)

**Comment by TrevCraw** [comment]
- [x] `For both start and finish project, you are supposed to configure the SDK.`
Rephrase to `The SDK should be configured for both the start and finish projects.`

- [x] Also, add `Click OK to save changes.` at the end of the SDK section. After `...specify the path to the Java 8 JDK downloaded on your computer.`

**Comment by TrevCraw** [comment]
For the "Try What You'll Build" section: 

- [x] The sentence `Try look at the console out for the Run finish.` should be `Look at the console out for the Run finish command.`

- [x] This sentence `The tool window will be activated by default displaying a console which allows you to follow the progress of the build.` should have a comma after `default`.

- [x] This line, `You are expected to see the system properties with the format of JSON Strings.` would sound better with `...system properties displayed in JSON format.`

**Comment by TrevCraw** [comment]
For the "Configuring the Server" section:

- [x] `Select View in the menu bar and navigate to Tool Windows and click Project to show up the Project Tool Window...` should say `display` instead of `show up`.

- [x] Also, for the above sentence, we should add `If the Project Tool Window is not currently displayed, select View in the menu bar....` , because we have already given these instructions earlier in the guide to display the `Project Tool Window`.

- [x] `The Open Liberty server was started in development mode at the beginning of the guide...` should say `The Open Liberty server was started in development mode in the previous section...`

- [x] As with the previous section, the line `You are expected to see the system properties with the format of JSON Strings.` would sound better with `...system properties displayed in JSON format.`

**Comment by TrevCraw** [comment]
"Debugging the microservice" section:

- [x] Similar to one of the previous comments, I think the order of the fields should be changed to be top to bottom: `Type 7777 into the Port field and Check in the Name field.` should have Name first, then Port.

- [x] We should also tell the user to remove the breakpoint they added, otherwise they will hit it when running the tests in the next section and the tests will timeout and fail.

**Comment by TrevCraw** [comment]
"Testing the microservice" section:

- [x] `In this example, you will create a test that does the latter.` - This is not accurate. It's better to say `...you will run a test that does the latter.`

- [x] `Since you started Open Liberty in development mode at the start of the guide...` - Again, not accurate, better to say `...earlier in the guide...`

- [x] At the part where we ask the user to run the tests using the Enter key, we should explain that they need to navigate to the `Run` window at the bottom and select the tab for `Develop start` to get back to the terminal where development mode is running.
![image](https://user-images.githubusercontent.com/5885743/72747910-e65f9600-3b83-11ea-9bbb-1530a1bfcbca.png)

- [ ] For `...change the existing assertion to a constant value that doesn't match the os.name system property.`
the text `existing assertion` should be a hotspot that points to the referred to assertion in the code on the right hand window.

**Comment by jj-zhang** [comment]
> * [ ]  `You can also use the icons on the toolbar to toggle quickly between the different configurations that were set up previously.`
> 
> Does this mean the drop down menu in the toolbar?
> ![image](https://user-images.githubusercontent.com/5885743/72652063-5804cd80-3953-11ea-88b9-745ee506b21b.png)

Yes, I think so.

**Comment by TrevCraw** [comment]
Opened a PR with changes here: https://github.com/OpenLiberty/draft-guide-intellij/pull/28

**Comment by TrevCraw** [comment]
- [x] Fix assertion
- [x] Improve IntelliJ definition/explanation

**Comment by TrevCraw** [comment]
I have concluded my review. The changes look good.
@jj-zhang The rest of the checklist appears to be your responsibility.
